### ISSUE TITLE
pypi tarballs are missing test/__init__.py

### ISSUE THREAD

**Issue by mgorny** [tych0/xcffib#106]
The sdist tarballs uploaded to pypi are missing `test/__init__.py` file. As a result, tests don't run out of the box:

```
$ nosetests 
EEEE
======================================================================
ERROR: Failure: ImportError (attempted relative import with no known parent package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.9/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/xcffib-0.10.0/test/test_connection.py", line 23, in <module>
    from .testing import XcffibTest
ImportError: attempted relative import with no known parent package

======================================================================
ERROR: test_crazy_window_script.TestWindow.test_the_script
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/lib/python3.9/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/tmp/xcffib-0.10.0/xcffib/testing.py", line 65, in setUp
    self._display, self._display_lock = find_display()
  File "/tmp/xcffib-0.10.0/xcffib/testing.py", line 34, in find_display
    f = open(lock_path(display), "w+")
PermissionError: [Errno 13] Permission denied: '/tmp/.X10-lock'

======================================================================
ERROR: Failure: ImportError (attempted relative import with no known parent package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.9/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/xcffib-0.10.0/test/test_fakeinput.py", line 5, in <module>
    from .testing import XcffibTest
ImportError: attempted relative import with no known parent package

======================================================================
ERROR: Failure: ImportError (attempted relative import with no known parent package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.9/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/xcffib-0.10.0/test/test_python_code.py", line 23, in <module>
    from .testing import XcffibTest
ImportError: attempted relative import with no known parent package

----------------------------------------------------------------------
Ran 4 tests in 0.023s

FAILED (errors=4)
```

**Comment by tych0** [comment]
Weird, I used the same release process I always do (albeit from python 3.8 and a newer setuptools). Have you encountered this elsewhere?

**Comment by mgorny** [comment]
It is missing in earlier releases too, since 0.4.2 at least judging by my predecessor patching it.
