### ISSUE TITLE
AttributeError: 'ClientMessageEvent' object has no attribute 'known_max'

### ISSUE THREAD

**Issue by Narrat** [tych0/xcffib#40]
Hi

Trying to run a program with xcffib fails with this error:

>Traceback (most recent call last):
  File "/etc/xdg/caw/config.py", line 113, in <module>
    caw.mainloop()
  File "/usr/lib/python2.7/site-packages/caw/caw.py", line 406, in mainloop
    self._fdhandlers[fd](eventmask)
  File "/usr/lib/python2.7/site-packages/caw/caw.py", line 364, in _process_xevents
    event = xproto.ClientMessageEvent(event)
  File "/usr/lib/python2.7/site-packages/xcffib/xproto.py", line 810, in __init__
    xcffib.Event.__init__(self, unpacker)
  File "/usr/lib/python2.7/site-packages/xcffib/__init__.py", line 655, in __init__
    Protobj.__init__(self, unpacker)
  File "/usr/lib/python2.7/site-packages/xcffib/__init__.py", line 267, in __init__
    if unpacker.known_max is not None:
AttributeError: 'ClientMessageEvent' object has no attribute 'known_max'

Whereas xpyb is working in that case.

**Comment by tych0** [comment]
Urgh, thanks for pointing this out. The problem here is that the Events aren't keeping track of their own buffers (they track via unpackers), whereas I think xpyb events implement python2's buffer interface. I think the right solution here is to perhaps expose the unpacker functions at the protobj level. I'll try and write a patch this weekend and post it.

**Comment by tych0** [comment]
Hi, sorry for the delay. I think I've pushed a patch that fixes this, please let me know if you encounter any other issues. Thanks!
