### ISSUE TITLE
build error xcffib-0.2.2 with python-3.4 

### ISSUE THREAD

**Issue by jrazik** [tych0/xcffib#41]
Hello, 

I was trying to upgrade my version of xcffib from 0.2.0 to 0.2.2 but I got this build error.
`AttributeError: struct xcb_screen_iterator_t: 'module' object has no attribute '_cffi_layout_struct_xcb_screen_iterator_t'`

However, under python-2.7 it works. I don't understand why so.

Here is the output of the building.

```
xcffib-0.2.2]$ python3.4 ./setup.py build
running build
Traceback (most recent call last):
  File "./setup.py", line 56, in <module>
    cmdclass={'build': cffi_build},
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib64/python3.4/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "./setup.py", line 36, in finalize_options
    import xcffib
  File "/tmp/xcffib-0.2.2/xcffib/__init__.py", line 24, in <module>
    from .ffi import ffi, C, visualtype_to_c_struct  # noqa
  File "/tmp/xcffib-0.2.2/xcffib/ffi.py", line 256, in <module>
    """, libraries=['xcb'], modulename='_xcffib')
  File "/usr/lib64/python3.4/site-packages/cffi/api.py", line 367, in verify
    lib = self.verifier.load_library()
  File "/usr/lib64/python3.4/site-packages/cffi/verifier.py", line 97, in load_library
    return self._load_library()
  File "/usr/lib64/python3.4/site-packages/cffi/verifier.py", line 207, in _load_library
    return self._vengine.load_library()
  File "/usr/lib64/python3.4/site-packages/cffi/vengine_cpy.py", line 160, in load_library
    self._load(module, 'loading')
  File "/usr/lib64/python3.4/site-packages/cffi/vengine_cpy.py", line 218, in _load
    method(tp, realname, module, **kwds)
  File "/usr/lib64/python3.4/site-packages/cffi/vengine_cpy.py", line 440, in _loading_cpy_struct
    self._loading_struct_or_union(tp, 'struct', name, module)
  File "/usr/lib64/python3.4/site-packages/cffi/vengine_cpy.py", line 517, in _loading_struct_or_union
    function = getattr(module, layoutfuncname)
AttributeError: struct xcb_screen_iterator_t: 'module' object has no attribute '_cffi_layout_struct_xcb_screen_iterator_t'
```

**Comment by flacjacket** [comment]
This is a known problem with upgrading to 0.2.2 if you have xcffib installed already, if you first uninstall xcffib, you should be able to re-install it fine.

**Comment by jrazik** [comment]
Thank you, it works fine !!
