### ISSUE TITLE
qtile xfce4-panel poll exception

### ISSUE THREAD

**Issue by nfnty** [tych0/xcffib#66]
xfce4-panel is unable to start and freezes when run under python 3.5.1 (tested previously with 2.7 with same result), qtile master and xcffib master. Tell me what debug information you need to track this down.

qtile output:
```
2016-02-10 04:14:30,998 libqtile manager.py:_xpoll():L748  Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/libqtile/manager.py", line 713, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.5/site-packages/xcffib/__init__.py", line 548, in wrapper
    return f(*args)
  File "/usr/lib/python3.5/site-packages/xcffib/__init__.py", line 589, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3.5/site-packages/xcffib/__init__.py", line 659, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3.5/site-packages/xcffib/__init__.py", line 625, in _process_error
    raise error(buf)
xcffib.xproto.ValueError
```
xfce4-panel output:
```
(xfce4-panel:17511): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 0
```

**Comment by tych0** [comment]
To debug this we'd need an xtrace: http://docs.qtile.org/en/latest/manual/hacking.html#capturing-an-xtrace

Also, I'll close this, since this is a qtile issue and not an xcffib issue.
