### ISSUE TITLE
X-Resource: protocol / data size mismatch error

### ISSUE THREAD

**Issue by orbisvicis** [tych0/xcffib#71]
```python
>>> import xcffib, xcffib.xproto, xcffib.res
>>> connection = xcffib.connect()
>>> resext = connection(xcffib.res.key)
>>> spec = xcffib.res.ClientIdSpec.synthetic(0x0190000c, xcffib.res.ClientIdMask.LocalClientPID)
>>> cookie = resext.QueryClientIds(1, [spec])
>>> reply = cookie.reply()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/__init__.py", line 324, in reply
    return self.reply_type(data)
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/res.py", line 208, in __init__
    self.ids = xcffib.List(unpacker, ClientIdValue, self.num_ids)
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/__init__.py", line 410, in __init__
    item = typ(unpacker)
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/res.py", line 79, in __init__
    self.value = xcffib.List(unpacker, "I", self.length)
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/__init__.py", line 407, in __init__
    self.list = list(unpacker.unpack(typ * count))
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/__init__.py", line 109, in unpack
    self._resize(size)
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/__init__.py", line 141, in _resize
    assert self.size + increment <= self.known_max
AssertionError
```

**Comment by orbisvicis** [comment]
```
QueryClientIdsReply :: self.length = 4
QueryClientIdsReply :: self.bufsize = 48
QueryClientIdsReply :: base = unpacker.offset = 0
QueryClientIdsReply :: self.num_ids = ... = 1
ClientIdValue :: base = unpacker.offset = 32
ClientIdSpec :: base = unpacker.offset = 32
ClientIdSpec :: self.client = ... = 41943040
ClientIdSpec :: self.mask = ... = 2
ClientIdSpec :: self.bufsize = unpacker.offset - base = 8
ClientIdValue :: unpacker.offset = ... = 40
ClientIdValue :: self.length = ... = 4
ClientIdValue :: unpacker.offset = ... = 44
ClientIdValue :: i1 = (3290,)
ClientIdValue :: unpacker.offset = ... = 48
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/__init__.py", line 324, in reply
    return self.reply_type(data)
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/res.py", line 232, in __init__
    self.ids = xcffib.List(unpacker, ClientIdValue, self.num_ids)
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/__init__.py", line 410, in __init__
    item = typ(unpacker)
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/res.py", line 90, in __init__
    i2 = unpacker.unpack("I")
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/__init__.py", line 109, in unpack
    self._resize(size)
  File "/home/orbisvicis/test-xcb/venv-3.4-cffib/lib/python3.4/site-packages/xcffib/__init__.py", line 141, in _resize
    assert self.size + increment <= self.known_max
AssertionError
```

The generated *xcffib/res.py* seems correct according to *resproto.txt*, */usr/include/xcb/res.h*, and */usr/share/xcb/res.xml*. `Unpacker.unpack` and `Unpacker.pad` aren't skipping any bytes. If I change **unpacker.known_max** to **60** in `QueryClientIdsReply`, then I get this:

```
QueryClientIdsReply :: self.length = 4
QueryClientIdsReply :: self.bufsize = 60
QueryClientIdsReply :: base = unpacker.offset = 0
QueryClientIdsReply :: self.num_ids = ... = 1
ClientIdValue :: base = unpacker.offset = 32
ClientIdSpec :: base = unpacker.offset = 32
ClientIdSpec :: self.client = ... = 41943040
ClientIdSpec :: self.mask = ... = 2
ClientIdSpec :: self.bufsize = unpacker.offset - base = 8
ClientIdValue :: unpacker.offset = ... = 40
ClientIdValue :: self.length = ... = 4
ClientIdValue :: unpacker.offset = ... = 44
ClientIdValue :: i1 = (3290,)
ClientIdValue :: unpacker.offset = ... = 48
ClientIdValue :: i2 = (64,)
ClientIdValue :: unpacker.offset = ... = 52
ClientIdValue :: i3 = (0,)
ClientIdValue :: unpacker.offset = ... = 56
ClientIdValue :: i4 = (1585,)
ClientIdValue :: unpacker.offset = ... = 60
QueryClientIdsReply :: self.bufsize = unpacker.offset - base = 60
```

*resproto.txt* states

> value
>     Actual ID data. In version 1.2 this is missing for ClientXid and
>     consists of a single CARD32 for LocalClientPid.

Notice the last three CARD32 are junk values. The core protocol says:

> Unused bytes within a reply are not guaranteed to be zero

But is it possible *XCB* fails to send the last three CARD32s? Either that or *xcffib* isn't reading the length of the response correctly...

**Comment by orbisvicis** [comment]
`Connection.wait_for_reply` has the comment:

>        # why is this 32 and not sizeof(xcb_generic_reply_t) == 8?

This is probably because, according to the core protocol:

>    Every reply consists of
32 bytes followed by zero or more additional bytes of data, as specified in the length field.

Anyway, `Connection.wait_for_reply` seems to be calculating the length correctly...

**Comment by orbisvicis** [comment]
C version of `QueryClientIds` returns **xcb_res_client_id_value_t.length** of **4** in this case. The bytes aren't directly accessible (use `xcb_res_client_id_value_value`), so I'd have to use xtrace to ensure four bytes are actually sent. It's a bit annoying that the index of the [CARD32 containing the valid PID] in LISTofCARD32 isn't specified. Perhaps 4 bytes aren't sent, and the getter function just "extrapolates" the correct data...

In other cases I'm seeing some unspecified data from `xcb_res_query_client_ids_reply`:

1.  **xcb_res_client_id_spec_t.mask == 2**: **xcb_res_client_id_value_t.length == 4**

    Expected

2.  **xcb_res_client_id_spec_t.mask == 0**: **xcb_res_client_id_value_t.length == 0**

    Unexpected in CLIENTIDVALUE. 0 implies all supported methods, but I specified `LocalClientPID` to `XResQueryClientIds`. Shouldn't all the results be `LocalClientPID` instead of 0?

3.  **xcb_res_client_id_spec_t.mask == \<big number\>**: **xcb_res_client_id_value_t.length == 2**

    Unexpected, the only valid mask values are [0, 1, 2, 3]. This is completely against the specification

**Comment by orbisvicis** [comment]
C version:

```
000:<:0001: 20: Request(98): QueryExtension name='X-Resource'
000:>:0001:32: Reply to QueryExtension: present=true(0x01) major-opcode=148 first-event=0 first-error=0
000:<:0002: 16: X-Resource-Request(148,4): UNKNOWN opcode=0x94 opcode2=0x04 unparsed-data=0x01,0x00,0x00,0x00,0x1f,0x00,0xc0,0x01,0x02,0x00,0x00,0x00;
000:>:0002:48: unexpected Reply: data1=0x01 data2=0x00 unparsed-data=0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xc0,0x01,0x02,0x00,0x00,0x00,0x04,0x00,0x00,0x00,0x23,0x0b,0x00,0x00;
```

xcffib version:
```
000:<:0001: 20: Request(98): QueryExtension name='X-Resource'
000:>:0001:32: Reply to QueryExtension: present=true(0x01) major-opcode=148 first-event=0 first-error=0
000:<:0002: 20: Request(98): QueryExtension name='X-Resource'
000:>:0002:32: Reply to QueryExtension: present=true(0x01) major-opcode=148 first-event=0 first-error=0
000:<:0003: 16: X-Resource-Request(148,4): UNKNOWN opcode=0x94 opcode2=0x04 unparsed-data=0x01,0x00,0x00,0x00,0x1f,0x00,0xc0,0x01,0x02,0x00,0x00,0x00;
000:>:0003:48: unexpected Reply: data1=0x01 data2=0x00 unparsed-data=0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xc0,0x01,0x02,0x00,0x00,0x00,0x04,0x00,0x00,0x00,0x23,0x0b,0x00,0x00;
```

Aside from the extra QueryExtension by *xcffib*, both are identical.

**Comment by orbisvicis** [comment]
Semi-parsed output from *x11trace*:

```
000:>:0000000000000003:0000000000000048: unexpected Reply: data1=0x01 data2=0x00 unparsed-data=0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xc0,0x01,0x02,0x00,0x00,0x00,0x04,0x00,0x00,0x00,0x23,0x0b,0x00,0x00;
```

Converted to fully unparsed, and annotated:
```
0x01,0x00,0x03,0x00,0x30,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xc0,0x01,0x02,0x00,0x00,0x00,0x04,0x00,0x00,0x00,0x23,0x0b,0x00,0x00;
|-------- xcb_generic_reply_t --------|                                                                                                                                                                                                        
|------------------------------------------------ xcb_res_query_client_ids_reply_t ---------------------------------------------------------------------------| |------------------xcb_res_client_id_value_t -------------|                    
                                                                                                                                                                |----- xcb_res_client_id_spec_t ------|                                        
|--| |--| |-------| |-----------------| |-----------------| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |--| |-----------------| |-----------------| |-----------------| |-----------------|
 type      sequence  length              num_ids             pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  pad  client              mask                length              value #1          
      pad0                                                   #01  #02  #03  #04  #05  #06  #07  #08  #09  #10  #11  #12  #13  #14  #15  #16  #17  #18  #19  #20                                                                                
 
 C8   C8   CARD16    CARD32              CARD32              C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   C8   CARD32              CARD32              CARD32              CARD32            
```

Notes: response length is **48** bytes instead of the expected **60**. The difference of **12** bytes is in the three missing CARD32 (CARD32 == 4 bytes) values. Specifically, when `reply.client_ids[*].length == 4`, the values `reply.client_ids[*].value[1:4]` are missing.

Anyway, the fault lies in the XCB XML interface specification. Except at the protocol level, none of the PID values are directly accessible. The C library provides the getter function `xcb_res_client_id_value_value` instead of exposing the memory directly, i.e. via a struct. Therefore, the C library works correctly while all (presumably) bindings are affected.

The X-Resource protocol specification (*resproto.txt*) clearly states (I emboldened the relevant sections):

> CLIENTIDVALUE
> ...
> length
> &nbsp;&nbsp;&nbsp;&nbsp;Specifies the length of an ID **in units of CARD32**. The length
> &nbsp;&nbsp;&nbsp;&nbsp;depends on the ID type. In version 1.2 the lengths are 0 for
> &nbsp;&nbsp;&nbsp;&nbsp;ClientXid and **4 for LocalClientPid**. The length of ClientXid is 0
> &nbsp;&nbsp;&nbsp;&nbsp;because that is already stored in the spec field.
> value
> &nbsp;&nbsp;&nbsp;&nbsp;Actual ID data. In version 1.2 this is missing for ClientXid and
> &nbsp;&nbsp;&nbsp;&nbsp;consists of a **single CARD32 for LocalClientPid**.

Which is reflected in the xml (*xcb/res.xml*):

```xml
<struct name="ClientIdValue">
    <field type="ClientIdSpec" name="spec" />
    <field type="CARD32" name="length" />
    <list type="CARD32" name="value">
        <fieldref>length</fieldref>
    </list>
</struct>
```

Notice the 3rd emboldened section ("single CARD32 for LocalClientPid"). In relation to the previous section, I interpret that as: four CARD32 values, only the first of which contains LocalClientPid. However, it seems the protocol completely ignores the previous section, and sends only a single CARD32.

**Comment by tych0** [comment]
So it seems like this is a bug in the thing on the other end of the connection? I notice that your xtrace output (and your annotated struct) here were both saying the length was 48, which matches what xcffib thinks it is as well. Perhaps you want to mail  xcb@lists.freedesktop.org about this?

**Comment by orbisvicis** [comment]
@tych0: Yes, reported via IRC, guess I'll keep this issue as the dumping ground for further thoughts.

C client for testing:

```C
// Derived from http://stackoverflow.com/a/37309217
//  "python: PID to X11 Window ID using XResQueryClientIds"
// In turn derived from the DWM 6.1 swallowing patches
#include <xcb/xcb.h>
#include <xcb/res.h>
#include <stdio.h>

int main() {
    xcb_connection_t * connection = xcb_connect(NULL, NULL);
    // For x11trace
    //xcb_connection_t * connection = xcb_connect(":9", NULL);

    // Match a single XID -> PID
    //xcb_res_client_id_spec_t spec = { 0x01c0001f, XCB_RES_CLIENT_ID_MASK_LOCAL_CLIENT_PID};
    // Match all XIDs -> PIDs
    xcb_res_client_id_spec_t spec = { 0, XCB_RES_CLIENT_ID_MASK_LOCAL_CLIENT_PID};

    xcb_generic_error_t * err = NULL;
    xcb_res_query_client_ids_cookie_t cookie = xcb_res_query_client_ids(connection, 1, &spec);
    xcb_res_query_client_ids_reply_t *reply = xcb_res_query_client_ids_reply(connection, cookie, &err);

    if (reply == NULL) {
        fprintf(stderr, "Error\n");
        return -1;
    }

    printf("Reply   :: num_ids  :: from struct      :: %u\n", reply->num_ids);
    printf("Reply   :: num_ids  :: from function    :: %u\n", xcb_res_query_client_ids_ids_length(reply));
    printf("\n");

    uint32_t * pid = NULL;
    xcb_res_client_id_value_iterator_t it = xcb_res_query_client_ids_ids_iterator(reply);
    for (; it.rem; xcb_res_client_id_value_next(&it)) {
        xcb_res_client_id_value_t * value;
        value = it.data;
        spec  = value->spec;
        printf("Spec    :: client   :: %u\n", spec.client);
        printf("Spec    :: mask     :: %u\n", spec.mask);
        printf("Value   :: length   :: from struct      :: %u\n", value->length);
        printf("value   :: length   :: from function    :: %u\n", xcb_res_client_id_value_value_length(value));
        if (spec.mask & XCB_RES_CLIENT_ID_MASK_LOCAL_CLIENT_PID) {
            // value can't be accessed from struct
            pid = xcb_res_client_id_value_value(value);
            printf("Value   :: PID      :: from function    :: %u\n", *pid);
        } else {
            printf("Spec    :: client   : PID unsupported\n");
        }
        printf("\n");
    }
}
```

Python client for testing:

```python
import xcffib, xcffib.xproto, xcffib.res
connection = xcffib.connect()
resext = connection(xcffib.res.key)
spec = xcffib.res.ClientIdSpec.synthetic(0, xcffib.res.ClientIdMask.LocalClientPID)
cookie = resext.QueryClientIds(1, [spec])
reply = cookie.reply()

for value in reply.ids:
    client          = value.spec.client
    mask            = value.spec.mask
    length          = value.length
    length_actual   = len(value.value)
    print("client           :: {}".format(client))
    print("mask             :: {}".format(mask))
    print("length           :: {}".format(length))
    print("length_actual    :: {}".format(length_actual))
    if mask & xcffib.res.ClientIdMask.LocalClientPID:
        print("PID              :: {}".format(value.value[0]))
    else:
        print("spec             :: PID unsupported")
    print("\n")
```

The python client only works with the [patch provided pharris](https://gist.github.com/anonymous/82d40eab88c153c76fdacd0cd4737dd1), but then it works perfectly. The C client works, with some inconsistencies per [my above comment](https://github.com/tych0/xcffib/issues/71#issuecomment-220519755). It is possible the junk data from the C clients is the result of out-of-bound reads arising from the same issue. Are the *libxcb*  C bindings autogenerated, like the *xcffib*?

Thoughts on the patch:

1.  It works and matches the protocol, but its a bit confusing that the length field doesn't match the actual length
2.  I think *libxcb* needs fixing as well. The unrelated inconsistencies [mentioned above](https://github.com/tych0/xcffib/issues/71#issuecomment-220519755) don't occur in clients that use the patched XML bindings, but do in an example C client.

So if the C library needs to be fixed, might as well change the protocol to either fix the ClientIdValue.length field, or change ClientIdValue.value from LISTofCARD32 to just CARD32 ?

**Comment by tych0** [comment]
This is fixed by,

https://cgit.freedesktop.org/xcb/proto/commit/?id=f7948e355d85624c577d0fa63977b3bed4d6024f

and will (presumably) be fixed in the next release of xcb-proto, so I'm closing this here. Thanks for debugging!
